import { atom } from "jotai";

// export const expenseAtom = atom([
// 	{
// 		id: 1,
// 		amount: 45,
// 		expenseDescription: "Burger",
// 		expenseCategory: "Food",
// 		expenseType: "Debit",
// 		date: {
// 			day: "28",
// 			month: "01",
// 			year: "2025",
// 		},
// 		// dateTimestamp: number,
// 		// createdAt: string,
// 		// updatedAt: string,
// 		recurring: false,
// 		// frequency: string | null,
// 	},
// 	{
// 		id: 2,
// 		amount: 130,
// 		expenseDescription: "Lunch",
// 		expenseCategory: "Food",
// 		expenseType: "Debit",
// 		date: {
// 			day: "29",
// 			month: "01",
// 			year: "2025",
// 		},
// 		// dateTimestamp: number,
// 		// createdAt: string,
// 		// updatedAt: string,
// 		recurring: true,
// 		// frequency: string | null,
// 	},
// 	{
// 		id: 3,
// 		amount: 110,
// 		expenseDescription: "Dinner",
// 		expenseCategory: "Food",
// 		expenseType: "Debit",
// 		date: {
// 			day: "29",
// 			month: "01",
// 			year: "2025",
// 		},
// 		// dateTimestamp: number,
// 		// createdAt: string,
// 		// updatedAt: string,
// 		recurring: true,
// 		// frequency: string | null,
// 	},
// 	{
// 		id: 4,
// 		amount: 5000,
// 		expenseDescription: "Room Rent",
// 		expenseCategory: "Rent",
// 		expenseType: "Debit",
// 		date: {
// 			day: "10",
// 			month: "02",
// 			year: "2025",
// 		},
// 		// dateTimestamp: number,
// 		// createdAt: string,
// 		// updatedAt: string,
// 		recurring: true,
// 		// frequency: string | null,
// 	},
// 	{
// 		id: 5,
// 		amount: 50000,
// 		expenseDescription: "Salary",
// 		expenseCategory: "Salary",
// 		expenseType: "Credit",
// 		date: {
// 			day: "10",
// 			month: "02",
// 			year: "2025",
// 		},
// 		// dateTimestamp: number,
// 		// createdAt: string,
// 		// updatedAt: string,
// 		recurring: true,
// 		// frequency: string | null,
// 	},
// 	{
// 		id: 6,
// 		amount: 500,
// 		expenseDescription: "Metro Card Recharge",
// 		expenseCategory: "Travel",
// 		expenseType: "Debit",
// 		date: {
// 			day: "05",
// 			month: "02",
// 			year: "2025",
// 		},
// 		// dateTimestamp: number,
// 		// createdAt: string,
// 		// updatedAt: string,
// 		recurring: true,
// 		// frequency: string | null,
// 	},
// ]);

export const expenseAtom = atom([]);
